Update 0.19.3
AnacondaRecipes/scikit-image-feedstock pull request #13
Opened 2022-11-09 20:41 UTC by ViridianMelody

Testing previous update

2022-11-09 20:42 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_8d9mepbkin/clone/recipe/meta.yaml:138: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_8d9mepbkin/clone/recipe/meta.yaml:138: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-11-09 20:42 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_3eyk_hxqcl/clone/recipe/meta.yaml:140: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_3eyk_hxqcl/clone/recipe/meta.yaml:140: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>

2022-11-09 22:12 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_95pgq0j2d4/clone/recipe/meta.yaml:139: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_95pgq0j2d4/clone/recipe/meta.yaml:139: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>

2022-11-09 22:26 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_131ezqovu2/clone/recipe/meta.yaml:140: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_131ezqovu2/clone/recipe/meta.yaml:140: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-11-10 00:06 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_77kurq3z7t/clone/recipe/meta.yaml:145: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_77kurq3z7t/clone/recipe/meta.yaml:145: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>

2022-11-10 16:47 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_daol7pjjo6/clone/recipe/meta.yaml:144: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_daol7pjjo6/clone/recipe/meta.yaml:144: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-11-15 16:12 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_7bwr890ogr/clone/recipe/meta.yaml:144: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_7bwr890ogr/clone/recipe/meta.yaml:144: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>

2022-11-15 21:23 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_69klkv1ccj/clone/recipe/meta.yaml:144: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_69klkv1ccj/clone/recipe/meta.yaml:144: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-11-16 09:18 UTC, katietz requested changes

2022-11-16 09:18 UTC, katietz commented on recipe/meta.yaml
> +  ignore_run_exports:
this should be no longer needed, as we turned off those errors in abs.yaml

2022-11-21 18:23 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_1dfhfr3m65/clone/recipe/meta.yaml:141: missing_license_url: The recipe is missing a license_url
WARNING: /tmp/abs_1dfhfr3m65/clone/recipe/meta.yaml:141: missing_doc_source_url: The recipe is missing a doc_source_url
Warnings were found

</details>

2022-11-22 04:42 UTC, varlackc reviewed
It might be recomended to have two spaces between `pooch >=1.3.0` and the `#` symbol 
https://github.com/AnacondaRecipes/scikit-image-feedstock/blob/bb2dd3baf16ed01d29572d4bdc4d5a1014cb17fc/recipe/meta.yaml#L115

2022-11-22 08:30 UTC, katietz approved these changes

2022-11-22 09:05 UTC, skupr-anaconda approved these changes

2022-11-23 22:14 UTC, merged

2022-11-23 22:15 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: /tmp/abs_f45ewzebua/clone/recipe/meta.yaml:141: missing_doc_source_url: The recipe is missing a doc_source_url
WARNING: /tmp/abs_f45ewzebua/clone/recipe/meta.yaml:141: missing_license_url: The recipe is missing a license_url
Warnings were found

</details>